import type { Metadata } from 'next';

import './globals.css';
import Header from '@/components/layout/Header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ko'>
      <body>
        <Header />
        <div className='flex min-h-[cal(100vh-60px)] flex-col items-center px-6 py-6 md:px-8'>
          {children}
        </div>
      </body>
    </html>
  );
}
